# This workflow lints the project whenever pushes/pull requests occur on all
# branches except release and dev-stable
name: Lint Code Base

on: 
  push:
    branches-ignore:
      - 'release'
      - 'dev-stable'
  pull_request:
    branches-ignore:
      - 'release'
      - 'dev-stable'

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*.cs
          FILTER_REGEX_EXCLUDE: .*.meta
